package brental.util;
// Generated Jan 5, 2014 1:07:36 PM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * Auto generated by hbm2java
 */
public class Auto  implements java.io.Serializable {


     private Integer autoId;
     private double cenaZakopeni;
     private Date datumZakoupeni;
     private int lodeKapacita;
     private Date platnostTk;
     private String spz;

    public Auto() {
    }

	
    public Auto(double cenaZakopeni, Date datumZakoupeni, int lodeKapacita, String spz) {
        this.cenaZakopeni = cenaZakopeni;
        this.datumZakoupeni = datumZakoupeni;
        this.lodeKapacita = lodeKapacita;
        this.spz = spz;
    }
    public Auto(double cenaZakopeni, Date datumZakoupeni, int lodeKapacita, Date platnostTk, String spz) {
       this.cenaZakopeni = cenaZakopeni;
       this.datumZakoupeni = datumZakoupeni;
       this.lodeKapacita = lodeKapacita;
       this.platnostTk = platnostTk;
       this.spz = spz;
    }
   
    public Integer getAutoId() {
        return this.autoId;
    }
    
    public void setAutoId(Integer autoId) {
        this.autoId = autoId;
    }
    public double getCenaZakopeni() {
        return this.cenaZakopeni;
    }
    
    public void setCenaZakopeni(double cenaZakopeni) {
        this.cenaZakopeni = cenaZakopeni;
    }
    public Date getDatumZakoupeni() {
        return this.datumZakoupeni;
    }
    
    public void setDatumZakoupeni(Date datumZakoupeni) {
        this.datumZakoupeni = datumZakoupeni;
    }
    public int getLodeKapacita() {
        return this.lodeKapacita;
    }
    
    public void setLodeKapacita(int lodeKapacita) {
        this.lodeKapacita = lodeKapacita;
    }
    public Date getPlatnostTk() {
        return this.platnostTk;
    }
    
    public void setPlatnostTk(Date platnostTk) {
        this.platnostTk = platnostTk;
    }
    public String getSpz() {
        return this.spz;
    }
    
    public void setSpz(String spz) {
        this.spz = spz;
    }




}


