package brental.util;
// Generated Jan 5, 2014 1:07:36 PM by Hibernate Tools 3.6.0



/**
 * Lod generated by hbm2java
 */
public class Lod  implements java.io.Serializable {


     private int lodId;
     private TypVybaveni typVybaveni;
     private double delka;
     private double maxPonor;
     private String model;
     private int nosnostOsob;
     private double sirka;
     private String typ;
     private String vyrobce;

    public Lod() {
    }

    public Lod(TypVybaveni typVybaveni, double delka, double maxPonor, String model, int nosnostOsob, double sirka, String typ, String vyrobce) {
       this.typVybaveni = typVybaveni;
       this.delka = delka;
       this.maxPonor = maxPonor;
       this.model = model;
       this.nosnostOsob = nosnostOsob;
       this.sirka = sirka;
       this.typ = typ;
       this.vyrobce = vyrobce;
    }
   
    public int getLodId() {
        return this.lodId;
    }
    
    public void setLodId(int lodId) {
        this.lodId = lodId;
    }
    public TypVybaveni getTypVybaveni() {
        return this.typVybaveni;
    }
    
    public void setTypVybaveni(TypVybaveni typVybaveni) {
        this.typVybaveni = typVybaveni;
    }
    public double getDelka() {
        return this.delka;
    }
    
    public void setDelka(double delka) {
        this.delka = delka;
    }
    public double getMaxPonor() {
        return this.maxPonor;
    }
    
    public void setMaxPonor(double maxPonor) {
        this.maxPonor = maxPonor;
    }
    public String getModel() {
        return this.model;
    }
    
    public void setModel(String model) {
        this.model = model;
    }
    public int getNosnostOsob() {
        return this.nosnostOsob;
    }
    
    public void setNosnostOsob(int nosnostOsob) {
        this.nosnostOsob = nosnostOsob;
    }
    public double getSirka() {
        return this.sirka;
    }
    
    public void setSirka(double sirka) {
        this.sirka = sirka;
    }
    public String getTyp() {
        return this.typ;
    }
    
    public void setTyp(String typ) {
        this.typ = typ;
    }
    public String getVyrobce() {
        return this.vyrobce;
    }
    
    public void setVyrobce(String vyrobce) {
        this.vyrobce = vyrobce;
    }




}


