package brental.util;
// Generated Jan 5, 2014 1:07:36 PM by Hibernate Tools 3.6.0



/**
 * Padlo generated by hbm2java
 */
public class Padlo  implements java.io.Serializable {


     private int padloId;
     private TypVybaveni typVybaveni;
     private double delka;
     private double sirkaListu;
     private String typ;

    public Padlo() {
    }

    public Padlo(TypVybaveni typVybaveni, double delka, double sirkaListu, String typ) {
       this.typVybaveni = typVybaveni;
       this.delka = delka;
       this.sirkaListu = sirkaListu;
       this.typ = typ;
    }
   
    public int getPadloId() {
        return this.padloId;
    }
    
    public void setPadloId(int padloId) {
        this.padloId = padloId;
    }
    public TypVybaveni getTypVybaveni() {
        return this.typVybaveni;
    }
    
    public void setTypVybaveni(TypVybaveni typVybaveni) {
        this.typVybaveni = typVybaveni;
    }
    public double getDelka() {
        return this.delka;
    }
    
    public void setDelka(double delka) {
        this.delka = delka;
    }
    public double getSirkaListu() {
        return this.sirkaListu;
    }
    
    public void setSirkaListu(double sirkaListu) {
        this.sirkaListu = sirkaListu;
    }
    public String getTyp() {
        return this.typ;
    }
    
    public void setTyp(String typ) {
        this.typ = typ;
    }




}


