package brental.util;
// Generated Jan 5, 2014 1:07:36 PM by Hibernate Tools 3.6.0



/**
 * Vesta generated by hbm2java
 */
public class Vesta  implements java.io.Serializable {


     private int vestaId;
     private TypVybaveni typVybaveni;
     private String typ;
     private double velikost;
     private String vyrobce;

    public Vesta() {
    }

    public Vesta(TypVybaveni typVybaveni, String typ, double velikost, String vyrobce) {
       this.typVybaveni = typVybaveni;
       this.typ = typ;
       this.velikost = velikost;
       this.vyrobce = vyrobce;
    }
   
    public int getVestaId() {
        return this.vestaId;
    }
    
    public void setVestaId(int vestaId) {
        this.vestaId = vestaId;
    }
    public TypVybaveni getTypVybaveni() {
        return this.typVybaveni;
    }
    
    public void setTypVybaveni(TypVybaveni typVybaveni) {
        this.typVybaveni = typVybaveni;
    }
    public String getTyp() {
        return this.typ;
    }
    
    public void setTyp(String typ) {
        this.typ = typ;
    }
    public double getVelikost() {
        return this.velikost;
    }
    
    public void setVelikost(double velikost) {
        this.velikost = velikost;
    }
    public String getVyrobce() {
        return this.vyrobce;
    }
    
    public void setVyrobce(String vyrobce) {
        this.vyrobce = vyrobce;
    }




}


