package brental.util;
// Generated Jan 5, 2014 1:07:36 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Zamestnanec generated by hbm2java
 */
public class Zamestnanec  implements java.io.Serializable {


     private Integer zamestnanecId;
     private String heslo;
     private String jmeno;
     private String login;
     private String pracovniPozice;
     private String ulice;
     private String mesto;
     private int psc;
     private String prijmeni;
     private Set fakturas = new HashSet(0);
     private Set rezervaces = new HashSet(0);

    public Zamestnanec() {
    }

	
    public Zamestnanec(String heslo, String jmeno, String login, String pracovniPozice, String ulice, String mesto, int psc, String prijmeni) {
        this.heslo = heslo;
        this.jmeno = jmeno;
        this.login = login;
        this.pracovniPozice = pracovniPozice;
        this.ulice = ulice;
        this.mesto = mesto;
        this.psc = psc;
        this.prijmeni = prijmeni;
    }
    public Zamestnanec(String heslo, String jmeno, String login, String pracovniPozice, String ulice, String mesto, int psc, String prijmeni, Set fakturas, Set rezervaces) {
       this.heslo = heslo;
       this.jmeno = jmeno;
       this.login = login;
       this.pracovniPozice = pracovniPozice;
       this.ulice = ulice;
       this.mesto = mesto;
       this.psc = psc;
       this.prijmeni = prijmeni;
       this.fakturas = fakturas;
       this.rezervaces = rezervaces;
    }
   
    public Integer getZamestnanecId() {
        return this.zamestnanecId;
    }
    
    public void setZamestnanecId(Integer zamestnanecId) {
        this.zamestnanecId = zamestnanecId;
    }
    public String getHeslo() {
        return this.heslo;
    }
    
    public void setHeslo(String heslo) {
        this.heslo = heslo;
    }
    public String getJmeno() {
        return this.jmeno;
    }
    
    public void setJmeno(String jmeno) {
        this.jmeno = jmeno;
    }
    public String getLogin() {
        return this.login;
    }
    
    public void setLogin(String login) {
        this.login = login;
    }
    public String getPracovniPozice() {
        return this.pracovniPozice;
    }
    
    public void setPracovniPozice(String pracovniPozice) {
        this.pracovniPozice = pracovniPozice;
    }
    public String getUlice() {
        return this.ulice;
    }
    
    public void setUlice(String ulice) {
        this.ulice = ulice;
    }
    public String getMesto() {
        return this.mesto;
    }
    
    public void setMesto(String mesto) {
        this.mesto = mesto;
    }
    public int getPsc() {
        return this.psc;
    }
    
    public void setPsc(int psc) {
        this.psc = psc;
    }
    public String getPrijmeni() {
        return this.prijmeni;
    }
    
    public void setPrijmeni(String prijmeni) {
        this.prijmeni = prijmeni;
    }
    public Set getFakturas() {
        return this.fakturas;
    }
    
    public void setFakturas(Set fakturas) {
        this.fakturas = fakturas;
    }
    public Set getRezervaces() {
        return this.rezervaces;
    }
    
    public void setRezervaces(Set rezervaces) {
        this.rezervaces = rezervaces;
    }




}


